# Generated by Django 4.2.15 on 2024-08-30 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='harvesting',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='input',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='marketing',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='processing',
            name='creator',
        ),
        migrations.AlterField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
