# Generated by Django 4.2.15 on 2025-02-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Production",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started", models.DateField(auto_now_add=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assignments.proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "PRODUCTION",
                "verbose_name_plural": "PRODUCTIONS",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Processing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_material", models.CharField(max_length=100)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("process", models.CharField(max_length=100)),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="individual_production.production",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing",
                "verbose_name_plural": "Processing",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Marketing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("unit", models.CharField(max_length=20)),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantity_sold", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quantity_given_out",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("quantity_lost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="individual_production.production",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marketing",
                "verbose_name_plural": "Marketing",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Input",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="resources.input",
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="individual_production.production",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Harvesting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("minutes_spent", models.IntegerField()),
                (
                    "harvest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="resources.harvest",
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="individual_production.production",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harvesting",
                "verbose_name_plural": "Harvesting",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strengths", models.TextField()),
                ("weaknesses", models.TextField()),
                ("opportunities", models.TextField()),
                ("threats", models.TextField()),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="individual_production.production",
                    ),
                ),
            ],
            options={
                "verbose_name": "SWOT",
                "verbose_name_plural": "SWOT Comments",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mortality", models.IntegerField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="resources.activity",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_related",
                        to="resources.material",
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="individual_production.production",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "abstract": False,
            },
        ),
    ]
