# Generated by Django 4.2.15 on 2024-08-25 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teamwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.crop')),
                ('livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.livestock')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.location')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.team')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.timeline')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.location')),
                ('miscellaneous_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.team')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.timeline')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('comments_by_supervisor', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.crop')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.file')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.livestock')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.location')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.timeline')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.unit')),
            ],
        ),
    ]
