# Generated by Django 4.2.15 on 2024-08-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamwork',
            name='title',
            field=models.CharField(default='Unnamed Task', max_length=24),
            preserve_default=False,
        ),
    ]
