# Generated by Django 4.2.15 on 2024-08-31 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0002_teamwork_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='supervisors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
