# Generated by Django 4.2.15 on 2024-08-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_special_supervisors'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='title',
            field=models.CharField(default='Unnamed', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='special',
            name='title',
            field=models.CharField(default='Unnamed', max_length=24),
            preserve_default=False,
        ),
    ]
