# Generated by Django 4.2.15 on 2024-08-31 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_unit_supervisor'),
        ('assignments', '0004_proposal_title_special_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.location'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='task',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='timeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.timeline'),
        ),
    ]
