# Generated by Django 4.2.15 on 2024-08-31 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_unit_supervisor'),
        ('assignments', '0005_alter_proposal_location_alter_proposal_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.unit'),
        ),
    ]
